services:
  jellyfin-uploader:
    image: jellyfin-uploader:latest
    build: .
    container_name: jellyfin-uploader
    ports:
      - "${PORT:-8080}:8080"
    logging:
      options:
        max-size: 10m
    env_file: .env
    restart: unless-stopped
